---
title: "Untitled"
author: "Yoon-dohee"
date: '2022-05-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 9-1
#a
```{r}
x1 = c(15, 20, 11, 23, 16, 21, 18, 16, 27, 24)
x2 = c(23, 31, 13, 19, 23, 17, 28, 26, 25, 28)
alpha = 0.05
n1 = length(x1)
n2 = length(x2)

#H0: u1 >= u2 ,  H1: u1 < u2

t.test(x1, x2) # Welch t-test
qt(1 - alpha, n1 + n2 - 2)
print("-1.806 < -1.734, H0 기각 -> 적다")
```

#c 
```{r}
#도희야! 이거 생략해? 말아? !!!!!
## ++ 일단 써야겠어
print("두 정규모집단은 독립적이며 X, Y는 등분산이다")
```

#c
```{r}
x1 = c(15, 20, 11, 23, 16, 21, 18, 16, 27, 24)
x2 = c(23, 31, 13, 19, 23, 17, 28, 26, 25, 28)
t.test(x1, x2) # Welch t-test
print("따라서, (-9.0942044, 0.6942044)")
```


# 9-2
#a

# 도희야 이거 답지가 틀렸다 내가맞음!

```{r}
#H0: u1>=u2, H1: u1<u2
x1 = c(65, 70, 76, 63, 72, 71, 68, 68)
x2 = c(75, 80, 72, 77, 69, 81, 71, 78)
alpha = 0.05 #default
t.test(x1, x2)
qt(1 - alpha, n1 + n2 - 2)

print("-2.9536 < 1.76131이므로 새로운 강의방식은 독해력 향상에 도움이 있다")
```

#b
```{r}
print("두 정규모집단은 독립적이며 X, Y는 등분산이다")
```

# 9-3
#a
#답 다른거 암
```{r}
nm = 15
nf = 16
mbar = 4.8
fbar = 4.4
sm = 0.8
sf = 0.9
alpha = 0.1

#H0: u1 = u2, H1: u1!=u2
#기각역 abs(T) >= t

sp = sqrt( ((nm - 1)*(sm^2) + (nf - 1)*(sf^2)) / (nm + nf - 2))
T = (mbar - fbar) / (sp * sqrt((1/nm) + (1/nf)));T

qt((1 - alpha/2), nm + nf - 2)

print("1.304487 < 1.699127이므로 H0 기각하지 않음 -> 다르다고 볼 수 없다")
```


#b
```{r}
nm = 15
nf = 16
mbar = 4.8
fbar = 4.4
sm = 0.8
sf = 0.9
alpha = 0.05

#H0: u1 = u2, H1: u1!=u2
#기각역 abs(T) >= t

sp = sqrt( ((nm - 1)*(sm^2) + (nf - 1)*(sf^2)) / (nm + nf - 2))
t = qt((1 - alpha/2), nm + nf - 2)
temp = t*sp*sqrt(1/nm + 1/nf);
x = c(-temp, temp)
(mbar - fbar) + x

```


# 9-4
#교수가 Z계산 말고 T분포 쓰라함
```{r}
nx = 40
ny = 42
xbar = 7.3
ybar = 8.9
sx = 1.1
sy = 1.2

#H0: ua = ub, H1 ua != ub
#기각역 abs(T) >= t

sp = sqrt( ((nx - 1)*(sx^2) + (ny - 1)*(sy^2)) / (nx + ny - 2))
T = (xbar - ybar) / (sp * sqrt((1/nx) + (1/ny))); T

qt((1 - alpha/2), nx + ny - 2)

print("T (abs(T) = 6.2847) > 1.96이므로, H0을 기각 -> 평균회복 시간에 차이가 있다.")

```


# 9-5
#a
```{r}
nx = 9
ny = 9
xbar = 39.8
ybar = 35.5
sx = 8.16
sy = 6.93
alpha = 0.05

#H0: ua = ub, H1 ua != ub
#기각역 abs(T) >= t

sp = sqrt( ((nx - 1)*(sx^2) + (ny - 1)*(sy^2)) / (nx + ny - 2))
T = (xbar - ybar) / (sp * sqrt((1/nx) + (1/ny))); T 

qt((1 - alpha/2), nx + ny - 2)

print("T (abs(T) = 1.204974) < 2.119905 이므로, H0을 기각하지 않음 -> 저조하다 볼 수 없음.")

```

#b
```{r}
nx = 9
ny = 9
xbar = 39.8
ybar = 35.5
sx = 8.16
sy = 6.93
alpha = 0.05

#H0: ua = ub, H1 ua != ub
#기각역 abs(T) >= t

sp = sqrt( ((nx - 1)*(sx^2) + (ny - 1)*(sy^2)) / (nx + ny - 2))
t = qt((1 - alpha/2), nx + ny - 2)
temp = t * sp * sqrt(1/nx + 1/ny)
x = c(-temp, temp)
(xbar - ybar) + x

```

# 9-6
#a
```{r}
nx = 6
ny = 6
xbar = 60.8
ybar = 41.8
sx = 16.4
sy = 7.6
alpha = 0.05 # default



#H0: ua = ub, H1 ua != ub
#기각역 abs(T) >= t

sp = sqrt( ((nx - 1)*(sx^2) + (ny - 1)*(sy^2)) / (nx + ny - 2))
T = (xbar - ybar) / (sp * sqrt((1/nx) + (1/ny))); T 

qt((1 - alpha/2), nx + ny - 2)

print("T (abs(T) = 2.574787) > 2.228139 이므로, H0을 기각 -> 호르몬 받은 쥐의 체중증가가 많다고 볼 수 있다")
print("두 개의 모집단은 독립적인 정규 모집단이며, 등분산을 가져야 한다.")


x <- rnorm(6, mean = 60.8, sd = 16.4)
y <- rnorm(6, mean = 41.8, sd = 7.6)
var.test(x , y)
```

#b
#책 예제 9.7 위에 내용있는데 교수님이 좀 부정적으로 말씀하셔서, 책보고 수정하고싶다는 맘안들면 나둬도될듯
```{r}
print("var.test 함수를 통해 p값을 확인하여 0.5 이하이면 이분산, 이상이면 등분산으로 가정한다");
#이 방법은 옛날 방법이다.
x <- rnorm(6, mean = 60.8, sd = 16.4)
y <- rnorm(6, mean = 41.8, sd = 7.6)
var.test(x, y)
print("p값이 0.5이하이므로 가정이 틀렸다고 가정할 수 있다. (정확하지 않음)")
```

# 9-7
#a
```{r}
print("체중이 잘 늘거나 활동량이 높은 등 체중 검사에 영향을 미치는 요소가 임의의 한 조에 치우쳐지지 않도록 하여, 모든 쥐가 선택될 확률이 같도록 한다. 특정 6마리에게 호르몬이 공급된다면 비교가 정확하지 않게 된다")
```


#b
```{r}
print("보지 않고 임의로 공 6개를 뽑아 해당 번호의 쥐를 선별한다")
```


# 9-8
```{r}
nx = 65
ny = 53
xbar = 123
ybar = 132
sx = 21
sy = 30
alpha = 0.05 # default

#H0: ua = ub, H1 ua != ub
#기각역 abs(T) >= t

sp = sqrt( ((nx - 1)*(sx^2) + (ny - 1)*(sy^2)) / (nx + ny - 2))
T = (xbar - ybar) / (sp * sqrt((1/nx) + (1/ny))); T 

qt((1 - alpha/2), nx + ny - 2)

print("T (abs(T) = -1.912163) < 1.980626 이므로, H0을 기각하지 않음 -> 치료법에 차이가 있다고 볼 수 없다.")


x <- rnorm(nx, mean = xbar, sd = sx)
y <- rnorm(ny, mean = ybar, sd = sy)
var.test(x , y)
```




# 9-9
```{r}
x1 = c(90, 86, 72, 65, 44, 52, 46, 38, 43)
x2 = c(85, 87, 70, 62, 44, 53, 42, 35, 46)
d = x1 - x2
alpha = 0.05

n = length(d)
dbar = mean(d)
dsd = sd(d)
T1 = dbar / (dsd/sqrt(n));T1
qt(1 - alpha/2, n - 1)
print("T (abs(T) = 1.485563) < 2.306004 이므로, H0을 기각하지 않음 -> 암기법 간 차이가 있다고 볼 수 없다.")

##or
t.test(x1, x2)
```


#9-10
#a
```{r}
x1 = c(14, 12, 18, 16, 15)
x2 = c(16, 15, 17, 16, 14)
t.test(x1 - x2)
print("(-2.855595, 1.655595)")
```

#b
```{r}
x1 = c(14, 12, 18, 16, 15)
x2 = c(16, 15, 17, 16, 14)

nx = length(x1)
ny = length(x2)
xbar = mean(x1)
ybar = mean(x2)
sx = sd(x1)
sy = sd(x2)
alpha = 0.05

sp = sqrt( ((nx - 1)*(sx^2) + (ny - 1)*(sy^2)) / (nx + ny - 2)); sp
t = qt((1 - alpha/2), nx + ny - 2)
temp = t*sp*sqrt(1/nx + 1/ny)
x = c(-temp, temp)
(xbar - ybar) + x

##OR
t.test(x1, x2)
```

#c
```{r}
print("(a), 각 쌍들은 독립적이다. 한번씩의 검사횟수(각 쌍)에 있어서 두 실험 단위는 동질적이며, 서로 다른 검사 (다른 쌍)에 속한 실험단위는 이질적일 수 있다.")
print("(b), 방법 1, 2의 모집단은 서로 독립적이다.")
```

#9-11
#a
```{r}
x1 = c(140, 90, 125, 130, 95, 121, 85, 97, 131, 110)
x2 = c(130, 87, 110, 132, 96, 120, 86, 90, 129, 100)
d = x1 - x2
alpha = 0.05

n = length(d)
dbar = mean(d)
dsd = sd(d)
T1 = dbar / (dsd/sqrt(n));T1
qt(1 - alpha/2, n - 1)
print("T (abs(T) = 2.408374) > 2.262157 이므로, H0을 기각 -> 왼손의 악력이 오른손보다 강하다.")

## or
t.test(x1 - x2)
```

#b
#답지가 틀림
```{r}
x1 = c(140, 90, 125, 130, 95, 121, 85, 97, 131, 110)
x2 = c(130, 87, 110, 132, 96, 120, 86, 90, 129, 100)
d = x1 - x2
alpha = 0.05

n = length(d)
dbar = mean(d)
dsd = sd(d)
t = qt(1 - alpha/2, n - 1)
temp = t * dsd / sqrt(n)
x = c(-temp, temp)
dbar + x


## or
t.test(x1 - x2)
```

#9-12
#a
```{r}
# 평균증가 => u1 - u2 (delta)
# H0: delta = 0, H1 = delta > 0
xbar = 120.5
s = 198.7
n = 48
alpha = 0.05

T = xbar /(s / sqrt(n)); T
qt(1 - alpha/2, n - 1)
print("T (abs(T) = 4.201553) > 2.011741 이므로, H0을 기각 -> 선전이 판매고 증가 효과 있음.")
```

#b
#Z가 아니라 T로 계산해서 편차있음. 교수 love T
```{r}
# 평균증가 => u1 - u2 (delta)
# H0: delta = 0, H1 = delta > 0
xbar = 120.5
s = 198.7
n = 48
alpha = 0.05
t = qt(1 - alpha/2, n - 1)

temp = t * s / sqrt(n)
x = c(-temp, temp)
xbar + x
```

#9-13
###### 책에 있는 걸로 앎. 이 단원 첫장과 226페이지르 ㄹ참고하였음
#a
```{r}
print("실험단위 : 16대의 차")
print("실험방법 :")
print("1. 16대의 차 중 임의로 8대를 추출. 이 때, 추출 과정에서 연비에 영향을 미치는 특성의 자동차가 한 실험군에 모이지 않게 뽑아야 함.")
print("2. 한 종류의 휘발유를 각각 일정량을 넣고 주행하여 주행거리 측정")
print("3. 나머지 8대에 다른 종류의 휘발유를 넣어 같은 방법으로 측정")
```

#b
# 이거 답지에는 좀 애매하게 나온거같은ㄷ 이건 직접 해주세용
```{r}
print("실험단위 : 40명의 7세 소년들에게 가르칠 방법 2개")
print("실험방법 :")
print("1. 40명 중 임의로 20명을 선발, 이 때 교육에 영향을 미치는 특성이 한 실험군에 모이지 않게 뽑아야 함.")
print("2. 각각의 실험군에 다른 방법의 스케이트 강의")
print("3. 결과를 측정하여 비교")
```


#9-14 
```{r}
require(PropCIs)
n1 = 500
x1 = 295
n2 = 100
x2 = 64
alpha = 0.01
x = c(x1, x2)
n = c(n1, n2)
prop.test(x, n)
```

```{r}
p1 = x1 / n1; p1
p2 = x2 / n2; p2
abs(p1 - p2)

zcut = qnorm(1 - alpha/2)
zcut * sqrt((p1*(1 - p1)/n1) + (p2 * (1 - p2) / n2))
```


#9-15
```{r}
n1 = 100
n2 = 100
x1 = 21
x2 = 38
alpha = 0.01
x = c(x1, x2)
n = c(n1, n2)
prop.test(x, n)
```


#a
```{r}
p1 = x1/n1
q1 = 1 - p1
p2 = x2/n2
q2 = 1 - p2

#H0: p1 = p2, H1: p1 < p2
#기각역: Z <= -za

Z = (p1 - p2) / (sqrt(p1*q1) * sqrt(1/n1 + 1/n2));Z
zcut = qnorm(1 - alpha/2);zcut

Z < -1 * zcut
print("2.951282 < -2.575829 이므로 H0기각 -> 신장에 이상있는 사람이 알레르기 반응 일어날 비율이 높다고 볼 수 있다.")

```

#b
```{r}
alpha = 0.05
diffscoreci(x1, n1, x2, n2, conf.level=1 - alpha) # best, recommended
```


#9-16
```{r}
x1 = c(15, 20, 11, 23, 16, 21, 18, 16, 27, 24)
x2 = c(23, 31, 13, 19, 23, 17, 28, 26, 25, 28)
alpha = 0.1
n1 = length(x1)
n2 = length(x2)
s1 = sd(x1)
s2 = sd(x2)


#기각역: 
#S1^2 / S2^2 >= F(n1 - 1, n2 - 1; alpha/2) //
#or
#S1^2 / S2^2 <= F(n1 - 1, n2 - 1; 1 - alpha/2)
# R에서는 alpha 반대로, 위 식은 일반 식

F1 = s1^2 / s2^2; F1
g1 = qf(1 - alpha/2, n1 -1, n2 -1); g1
g2 = qf(alpha/2, n1 -1, n2 -1); g2

F1 >= g1
F1 <= g2

print("기각역에 해당하지 않으므로 변이도에 차이가 있다고 볼 수 없다.")

## or
var.test(x1, x2)
```

#9-17
#a
```{r}
nx = 9
ny = 9
xbar = 39.8
ybar = 35.5
sx = 8.16
sy = 6.93
alpha = 0.05

#H1 deltax > deltay
#기각역 F>=F(n1-1, n2-1; a)

F1 = sx^2 / sy^2; F1
qf(1 - alpha, nx - 1, ny - 1)
print("1.386481 < 3.438101 이므로 H0 기각아님 -> 정상 세포활동 표준편차가 정신분열증 환자보다 크다고 볼 수 없다")
```

#b
```{r}
n1 = 9
n2 = 9
sx = 8.16
sy = 6.93
alpha = 0.1

F1 = sx^2 / sy^2
ci = c(F1/qf(1 - alpha/2, n1 - 1, n2 - 1), F1/qf(alpha/2, n1 - 1, n2 - 1))
sqrt(ci)
```


#9-18
#a
```{r}
x1 = c(0.95, 0.82, 0.78, 0.96, 0.71, 0.86, 0.99)
x2 = c(0.89, 0.91, 0.94, 0.91, 0.90, 0.89)
n1 = length(x1)
n2 = length(x2)
sd1 = sd(x1)
sd2 = sd(x2)
alpha = 0.05

#H0: deltaa = deltab, H1: deltaa < deltab

F1 = sd1^2 / sd2^2; F1
qf(1 - alpha/2, n1 - 1, n2 - 1)

print("31.31868 > 6.977702 이므로 H0 기각아님 -> 기계B 정밀도가 A보다 좋다고 볼 수 없다")
```

#b
```{r}
x1 = c(0.95, 0.82, 0.78, 0.96, 0.71, 0.86, 0.99)
x2 = c(0.89, 0.91, 0.94, 0.91, 0.90, 0.89)
n1 = length(x1)
n2 = length(x2)
sd1 = sd(x1)
sd2 = sd(x2)
alpha = 0.1


F1 = sd1^2 / sd2^2; F1
ci = c(F1/qf(1 - alpha/2, n1 - 1, n2 - 1), F1/qf(alpha/2, n1 - 1, n2 - 1))
sqrt(ci)
```
















